import json
import sqlite3
import requests as req

LINKS = [
    "?q=&client=class-search-ui&p={page}&campus=col&subject=acadaff",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=acctmis",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=accad",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=aeroeng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=afamast",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=aedecon",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=acel",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=agrcomm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=agsysmt",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ase",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=airsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=aminsts",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=asl",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=anatomy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=animsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=anthrop",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=arabic",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=arch",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=art",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=arteduc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=artssci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=asamsts",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=astron",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=athtrng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=atmossc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=aviatn",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biochem",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=bioethc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biophrm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biology",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=bmea",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biomede",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=bmi",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biomsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=bsgp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=biophys",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=bcs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=busoba",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=busfin",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=busmhr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=busml",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=busadm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cbg",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=catalan",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cllc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=chemphy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cbe",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=chem",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=chinese",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=crplan",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=civilen",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=clas",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mcr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=comm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=comldr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=compstd",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cse",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=consysm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cscffs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=csfrst",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cshspmg",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=consci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cstw",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=czech",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=dance",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=denthyg",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=dent",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=design",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=dsablst",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=earthsc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=eall",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=econ",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esce",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=escfe",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esepsy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=eseadm",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esepol",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=eshesa",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esltech",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esphe",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esqual",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esqrem",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=esspsy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=essped",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=eswde",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ehe",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=edutl",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=educst",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ece",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=engr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=engredu",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=english",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=entmlgy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=enr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=enveng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=envsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ethnstd",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=eeob",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=exp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=filmstd",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=fdscte",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=fabeng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=faes",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=french",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=frit",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=gened",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=geoscim",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=geog",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=german",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=gradsch",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=greek",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hcinnov",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hims",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hthrhsc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hw",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hebrew",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hindi",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=history",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=histart",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=honors",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hcs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=hdfs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=humnntr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ise",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=intmed",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=intstds",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=islam",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=italian",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=japanse",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=jewshst",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=kinesio",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=knhes",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=knpe",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=knsfhp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=knsism",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=know",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=korean",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=larch",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=latin",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=law",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ling",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mba",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mdn",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=matscen",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=math",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=meatsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mecheng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=meddiet",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=medlbs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=medcoll",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=medren",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=medmcim",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=micrbio",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=milsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mdrngrk",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mcdbio",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=molgen",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mvngimg",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=music",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=navalsc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nelc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=neursgy",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=neuro",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=neurosc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=neurogs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nuclren",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nursing",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nrsadvn",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nrsprct",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=occther",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=osbp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=optom",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=otolarn",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pathol",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=peds",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=persian",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=phr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=philos",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=physmed",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=physthr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=physics",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=physio",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=plntpth",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=polish",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=politsc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=portgse",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=psybhlh",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=psych",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhbio",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhehs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhepi",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhhbp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhhmp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubafrs",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=pubhlth",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=quechua",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=radonc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=radsci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=radiolg",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=relstds",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=respthr",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=romling",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=romania",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=rurlsoc",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=russian",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=sanskrt",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=scandvn",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=scholar",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=slavic",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=socwork",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=sociol",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=somali",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=sasia",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=spanish",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=sphhrng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=stat",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=surgery",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=swahili",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=swedish",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=theatre",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=gradtda",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=turkish",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=urdu",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=urology",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=uzbek",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=vetbios",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=vetclin",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=vmcoll",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=vetprev",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=vissci",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=weldeng",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=wgsst",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=yiddish",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=civicll",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=civictl",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=compedu",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=cybrsec",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=dne",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=mmt",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=nro",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tlcte",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tled",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tlielp",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tlistem",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tllll",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=tlted",
    "?q=&client=class-search-ui&p={page}&campus=col&subject=ukrain",
]

NAMES = [
    "Academic Affairs",
    "Accounting and Management Info",
    "Adv Computing Cntr Arts & Design",
    "Aerospace Engineering",
    "African American & African Std",
    "Agricul Envrmntl & Devlop Econ",
    "Agricultural Comm, Ed & Ldrshp",
    "Agricultural Communication",
    "Agricultural Systems Mgmt",
    "Agriscience Education",
    "Air Force Aerospace Studies",
    "American Indian Studies",
    "American Sign Language",
    "Anatomy",
    "Animal Sciences",
    "Anthropology",
    "Arabic",
    "Architecture",
    "Art",
    "Art Education",
    "Arts and Sciences",
    "Asian American Studies",
    "Astronomy",
    "Athletic Training",
    "Atmospheric Sciences",
    "Aviation",
    "Biochemistry",
    "Bioethics",
    "Biological Chem & Pharmacology",
    "Biology",
    "Biomedical Education",
    "Biomedical Engineering",
    "Biomedical Informatics",
    "Biomedical Science",
    "Biomedical Sciences Grad Prog",
    "Biophysics",
    "Bosnian/Croatian/Serbian",
    "Bus Admin: Operat & Bus Analyt",
    "Business Admin : Finance",
    "Business Admin : Mgmt & HR",
    "Business Admin:Marketing & Log",
    "Business Administration",
    "Cancer Biology and Genetics",
    "Catalan",
    "Center for Lang, Lit & Culture",
    "Chemical Physics",
    "Chemical and Biomolecular Eng",
    "Chemistry",
    "Chinese",
    "City and Regional Planning",
    "Civil Engineering",
    "Classics",
    "Clinical Research",
    "Communication",
    "Community Leadership",
    "Comparative Studies",
    "Computer Science & Engineering",
    "Construction Systems Mgmt",
    "Consumer Sci: Con & Fam Fin Serv",
    "Consumer Sci: Fashion & Retail",
    "Consumer Sci: Hospitality Mgt",
    "Consumer Sciences",
    "Ctr for Study & Teaching Writing",
    "Czech",
    "Dance",
    "Dental Hygiene",
    "Dentistry",
    "Design",
    "Disability Studies",
    "Earth Sciences",
    "East Asian Languages and Lit",
    "Economics",
    "Educ Sts: Counselor Education",
    "Educ Sts: Cultural Foundations",
    "Educ Sts: Education Psychology",
    "Educ Sts: Educational Admin",
    "Educ Sts: Educational Policy",
    "Educ Sts: Higher Ed & Stdt Aff",
    "Educ Sts: Learning Technologie",
    "Educ Sts: Philo & Hist of Educ",
    "Educ Sts: Qualitative Research",
    "Educ Sts: Qunt Rsch Eval & Msrmt",
    "Educ Sts: School Psychology",
    "Educ Sts: Special Education",
    "Educ Sts: Wkfrc Dvlpt & Educ",
    "Education and Human Ecology",
    "Education:Teaching & Learning",
    "Educational Studies",
    "Electrical and Computer Eng",
    "Engineering",
    "Engineering Education",
    "English",
    "Entomology",
    "Environment & Natural Resource",
    "Environmental Engineering",
    "Environmental Science",
    "Ethnic Studies",
    "Evol, Ecology & Organismal Bio",
    "Exploration",
    "Film Studies",
    "Food Science & Technology",
    "Food, Agricul & Bio Engineer",
    "Food, Agricul, & Enviro Sci",
    "French",
    "French and Italian",
    "General Education",
    "Geodetic Sciences MPS",
    "Geography",
    "German",
    "Graduate School",
    "Greek",
    "Health Care Innovation",
    "Health Info Mgt & Systems",
    "Health and Rehabilitation Sci",
    "Health and Wellness",
    "Hebrew",
    "Hindi",
    "History",
    "History of Art",
    "Honors, University",
    "Horticulture and Crop Science",
    "Human Dev and Family Science",
    "Human Nutrition",
    "Industrial and Sys Engineering",
    "Internal Medicine",
    "International Studies",
    "Islamic Studies",
    "Italian",
    "Japanese",
    "Jewish Studies",
    "Kinesiology",
    "Kinesiology: Health & Exercs Sci",
    "Kinesiology:Physical Education",
    "Kinesiology:Sprt, Ftns & Hlth Pr",
    "Kinesiology:Spt Indsty Spt Mgt",
    "Knowlton",
    "Korean",
    "Landscape Architecture",
    "Latin",
    "Law",
    "Linguistics",
    "Master of Business Admin",
    "Master of Dietetics & Nutritio",
    "Materials Science and Engineer",
    "Mathematics",
    "Meat Science",
    "Mechanical Engineering",
    "Medical Dietetics",
    "Medical Laboratory Science",
    "Medicine, College of",
    "Medieval & Renaissance Studies",
    "Microbial Infection & Immunity",
    "Microbiology",
    "Military Science",
    "Modern Greek",
    "Molec, Cellular, Dvlpmtl Bio",
    "Molecular Genetics",
    "Moving Image Production",
    "Music",
    "Naval Science",
    "Near Eastrn Lang and Cultures",
    "Neurological Surgery",
    "Neurology",
    "Neuroscience Department",
    "Neuroscience Graduate Studies",
    "Nuclear Engineering",
    "Nursing",
    "Nursing Advancement",
    "Nursing Practice",
    "Occupational Therapy",
    "Ohio State Biochemistry Prg",
    "Optometry",
    "Otolaryngology",
    "Pathology",
    "Pediatrics",
    "Persian",
    "Pharmacy",
    "Philosophy",
    "Physical Med & Rehabilitation",
    "Physical Therapy",
    "Physics",
    "Physiology and Cell Biology",
    "Plant Pathology",
    "Polish",
    "Political Science",
    "Portuguese",
    "Psychiatry and Behavioral Heal",
    "Psychology",
    "Pub Hlth: Biostatistics",
    "Pub Hlth: Envirmtl Hlth Scis",
    "Pub Hlth: Epidemiology",
    "Pub Hlth: Hlth Bhvr & Hlth Prom",
    "Pub Hlth: Hlth Srvcs Mgt & Plcy",
    "Public Affairs, John Glenn Sch",
    "Public Health",
    "Quechua",
    "RADONC",
    "Radiologic Sciences & Therapy",
    "Radiology",
    "Religious Studies",
    "Respiratory Therapy",
    "Romance Linguistics",
    "Romanian",
    "Rural Sociology",
    "Russian",
    "Sanskrit",
    "Scandinavian",
    "Scholars, University",
    "Slavic Languages & Literatures",
    "Social Work",
    "Sociology",
    "Somali",
    "South Asia Studies",
    "Spanish",
    "Speech and Hearing Science",
    "Statistics",
    "Surgery",
    "Swahili",
    "Swedish",
    "Theatre",
    "Translational Data Analytics",
    "Turkish",
    "Urdu",
    "Urology",
    "Uzbek",
    "Veterinary Biosciences",
    "Veterinary Clinical Sciences",
    "Veterinary Medicine",
    "Veterinary Preventive Medicine",
    "Vision Science",
    "Welding Engineering",
    "Women's, Gender & Sexuality Sts",
    "Yiddish",
    "civicll",
    "civictl",
    "compedu",
    "cybrsec",
    "dne",
    "mmt",
    "nro",
    "tlcte",
    "tled",
    "tlielp",
    "tlistem",
    "tllll",
    "tlted",
    "ukrain",
]


conn = sqlite3.connect("ge.db")

cur = conn.cursor()


# Make API request
def request(page, url):
    return json.loads(
        req.get(
            f"https://content.osu.edu/v2/classes/search{url.format(page=page)}"
        ).text
    )


# Write to file
def write(file, url, i):
    page = 1
    print(page)
    data = request(page, url)
    file.write(f"\n{NAMES[i]}\n\n")

    for course in data["data"]["courses"]:
        file.write(
            f"{course['course']['subject']} {course['course']['catalogNumber']}\n"
        )
        file.write(f"{course['course'].get('title', 'No Title')}\n")
        file.write(f"{course['course'].get('description', 'No description')}\n")

        for section in course.get("sections"):

            file.write(f"{section["classNumber"]}\n")
            file.write(f"{section["term"]}\n")

            for meeting in section.get("meetings"):
                file.write(f"{meeting["meetingNumber"]}\n")
                file.write(f"{meeting["monday"]}\n")
                file.write(f"{meeting["tuesday"]}\n")
                file.write(f"{meeting["wednesday"]}\n")
                file.write(f"{meeting["thursday"]}\n")
                file.write(f"{meeting["friday"]}\n")
                file.write(f"{meeting["saturday"]}\n")
                file.write(f"{meeting["sunday"]}\n")
                file.write(f"{meeting["startTime"]}\n")
                file.write(f"{meeting["endTime"]}\n")
                file.write(f"{meeting["facilityDescription"]}\n")
                file.write(f"{meeting["room"]}\n")

    while int(data["data"]["totalPages"]) > page:
        page = page + 1
        data = request(page, url)
        print(page)
        for course in data["data"]["courses"]:
            file.write(
                f"{course['course']['subject']} {course['course']['catalogNumber']}\n"
            )
            file.write(f"{course['course'].get('title', 'No Title')}\n")
            file.write(f"{course['course'].get('description', 'No description')}\n")
            for section in course.get("sections"):

                file.write(f"{section["classNumber"]}\n")
                file.write(f"{section["term"]}\n")

                for meeting in section.get("meetings"):
                    file.write(f"{meeting["meetingNumber"]}\n")
                    file.write(f"{meeting["startTime"]}\n")
                    file.write(f"{meeting["endTime"]}\n")
                    file.write(f"{meeting["monday"]}\n")
                    file.write(f"{meeting["tuesday"]}\n")
                    file.write(f"{meeting["wednesday"]}\n")
                    file.write(f"{meeting["thursday"]}\n")
                    file.write(f"{meeting["friday"]}\n")
                    file.write(f"{meeting["saturday"]}\n")
                    file.write(f"{meeting["sunday"]}\n")
                    file.write(f"{meeting["facilityDescription"]}\n")
                    file.write(f"{meeting["room"]}\n")


file = open("courses.txt", "w")

for i in range(len(NAMES)):
    write(file, LINKS[i], i)

file.close()
conn.close()
